name: Deploy to stage
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
        ECR_REGION_1:
            type: string
            default: us-east-1
        NODE_VERSION:
            type: number
            default: 18
        AC_IMAGE_VERSION:
            type: string
        AC_SERVICE_NAME:
            type: string
    secrets:
        AWS_ROLE_ARN:
            required: true

jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    outputs:
      production_version: ${{ steps.info.outputs.production_version }}
      staging_version: ${{ steps.info.outputs.staging_version }}
      deploy_version: ${{ steps.info.outputs.deploy_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: amdigital-co-uk/acif-deploy-tooling
          ref: feature/add-deploy-tooling-scripts
          path: common-build-tools

      - name: Configure AWS credentials (ECR_REGION_1)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ inputs.ECR_REGION_1 }}

      - name: Login to Amazon ECR (us-east-1)
        id: login-ecr-1
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Build deploy-tooling
        working-directory:  common-build-tools/deploy-tooling
        run: |
          npm install
          npm run build

      - name: Gather version info
        id: info
        working-directory:  common-build-tools/deploy-tooling
        run: |
          npm run --silent status > status.json
          production_version=$(cat status.json | jq -r .production.version)
          staging_version=$(cat status.json | jq -r .staging.version)
          echo "production_version=$production_version" >> $GITHUB_OUTPUT
          echo "staging_version=$staging_version" >> $GITHUB_OUTPUT
          echo "deploy_version=$AC_IMAGE_VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Echo version info in case of failure
        if: failure()
        working-directory:  common-build-tools/deploy-tooling
        run: |
          echo "---------------"
          cat status.json
          echo "---------------"
      - name: Deploy to stage
        working-directory:  common-build-tools/deploy-tooling
        run: |
          npm run stage-deploy $AC_IMAGE_VERSION