# CI workflow for 
name: Build and Deploy Function
permissions:
  id-token: write
  contents: read

# Define triggers for when the workflow will run
on:
  workflow_call:
    inputs:
      REF:
        type: string
      DK_NAMESPACE: # Docker Namespace: Typically this will be 'qtfn' for a lambda function
        required: true
        type: string
      DK_IMAGE:     # Docker Image
        required: true
        type: string
      DK_TAG:       # Docker Tag
        required: false
        type: string
        default: 'latest'
      WORKDIR:
        required: false
        type: string
        default: '.'
      ECR_REGION_1: # Primary AWS ECR region
        required: true
        type: string
      ECR_REGION_2: # Secondary AWS ECR region to push the Docker image to (optional)
        type: string
      BUILD_NPMRC:
        required: false
        type: boolean
        default: false
    secrets:
      PKG_TOKEN:
        required: false
      AWS_ROLE_ARN:
        required: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      REF: ${{ inputs.REF }}
      TAG: ${{ inputs.DK_TAG }}
    steps:
      # Checks-out repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}

      # Determine correct Docker tag based on branch/release
      ## NOTE: using the stage/* & main branching strategy
      - name: Set tag based on branch
        run: |
          if [[ "$REF" == refs/heads/* ]]
          then
            SCC_BRANCH=$(echo ${REF#refs/heads/})
            echo "Branch/Tag parsing: HEAD case -- REF=$REF"
          elif [[ "$REF" == refs/tags/* ]]
          then
            SCC_TAG=$(echo ${REF#refs/tags/})
            echo "Branch/Tag parsing: TAG case -- REF=$REF"
          else
            SCC_BRANCH=$REF
            echo "Branch/Tag parsing: DEFAULT case -- REF=$REF"
          fi
          [[ "$SCC_BRANCH" == stage/* ]] && TAG=$(echo ${SCC_BRANCH#stage/})
          [[ "$SCC_TAG" == v* ]] && TAG=$SCC_TAG
          echo "BRANCH=$SCC_BRANCH"
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
      
      # Login to ECR_REGION_1
      # See https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions
      - name: Configure AWS credentials (ECR_REGION_1)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ inputs.ECR_REGION_1 }}
      - name: Login to Amazon ECR (us-east-1)
        id: login-ecr-1
        uses: aws-actions/amazon-ecr-login@v1
        
      # Login to ECR_REGION_2
      - name: Configure AWS credentials (ECR_REGION_2)
        if: ${{ inputs.ECR_REGION_2 != '' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ inputs.ECR_REGION_2 }}
          
      - name: Login to Amazon ECR (us-east-2)
        if: ${{ inputs.ECR_REGION_2 != '' }}
        id: login-ecr-2
        uses: aws-actions/amazon-ecr-login@v1
          
      # Npmrc Setup
      - name: Npm Access Setup
        if: ${{ inputs.BUILD_NPMRC == true }}
        id: npmrcsetup
        run: |
          cd ${{ inputs.WORKDIR }}
          cat >.npmrc <<EOL
          //npm.pkg.github.com/:_authToken=${{ secrets.PKG_TOKEN }}
          @amdigital-co-uk:registry=https://npm.pkg.github.com/
          EOL
      
      # Build container via Docker & push to ECR
      - name: Build Docker Image
        id: build
        env:
          DK_NAMESPACE: ${{ inputs.DK_NAMESPACE }}
          DK_IMAGE: ${{ inputs.DK_IMAGE }}
          DK_REG_1: ${{ steps.login-ecr-1.outputs.registry }}
          DK_REG_2: ${{ steps.login-ecr-2.outputs.registry }}
        run: |
          cd ${{ inputs.WORKDIR }}
          docker build . -t $DK_REG_1/$DK_NAMESPACE/$DK_IMAGE:$TAG
          docker push $DK_REG_1/$DK_NAMESPACE/$DK_IMAGE:$TAG
          if [ -n "$ECR_REGION_2" ] && [ -n "$DK_REG_2" ] 
          then 
            docker tag $DK_REG_1/$DK_NAMESPACE/$DK_IMAGE:$TAG $DK_REG_2/$DK_NAMESPACE/$DK_IMAGE:$TAG
            docker push $DK_REG_2/$DK_NAMESPACE/$DK_IMAGE:$TAG
          fi
